story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story9.urls')),
    path('account/', include('django.contrib.auth.urls')),
]

story9/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "story9"

urlpatterns = [
    path('', views.index, name = "index"),
    path('register', views.register, name = "register"),
    path('logout', views.logout_view, name = 'logout'),
    path('nama', views.nama, name = "nama"),
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context = {
        "username" : request.user.username if request.user.is_authenticated else ""
    }
    return render(request, "index.html", context)

@login_required(login_url='/account/login')
def nama(request):
    vocals = ['a', 'i', 'u', 'e', 'o']
    name = request.user.username

    for ch in name.lower():
        if ch in vocals:
            name = name.replace(ch, 'x')

    context = {
        "username" : name
    }
    return render(request, "nama.html", context)

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            return redirect('account/login')

    else:
        form = UserCreationForm()

    context = {'form' : form}
    return render(request, "registration/register.html", context)

def logout_view(request):
    logout(request)
    return redirect('/')

story9/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Manrope&display=swap" rel="stylesheet">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    <title>Le Greeter</title>
  </head>
  <body class="min-vh-100 bg-secondary">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'story9:index' %}">Le Greeter</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <div class="ml-auto d-flex">
            {% if not request.user.is_authenticated %}
              <a class="mr-2" href="{% url 'story9:register' %}">
                <button id="register_button_nav" class="btn btn-secondary">
                    Register
                </button>
              </a>

              <a  href="{% url 'login' %}">
                <button id="login_button_nav" class="btn btn-secondary">
                    Login
                </button>
              </a>
            {% else %}
              <a href="{% url 'story9:logout' %}">
                <button id="logout_button_nav" class="btn btn-secondary">
                    Logout
                </button>
              </a>
            {% endif %}

            </div>
            </div>
        </div>
      </nav>

    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer class="page-footer font-small blue bg-dark text-light">

    </footer>
    <!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

story9/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="jumbotron rounded-0 text-light mb-0">
    <div class="container">
            {% if request.user.is_authenticated %}
            <h1 class="display-4">Selamat Datang, {{username}} !</h1>
            {% else %}
            <h1 class="display-4">Selamat Datang, 無名人 !</h1>
            {% endif %}
        </p>
    </div>
  </div>

  <section class="bottom-main bg-secondary content-bar text-light">
        <div class="container">
            {% if not request.user.is_authenticated %}
            <h3 class="pt-4">You are currently not logged in, <a href="{% url 'login' %}">Login here.</a></h3>
            {% endif %}
        </div>
  </section>

{% endblock %}

story9/templates/nama.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="jumbotron rounded-0 text-light mb-0">
    <div class="container">
        <h1 class="display-4">Selamat Datang, {{username}} !</h1>
        </p>
    </div>
  </div>

  <section class="bottom-main bg-secondary content-bar text-light">
        <div class="container">
            {% if not request.user.is_authenticated %}
            <h3 class="pt-4">You are currently not logged in, <a href="{% url 'login' %}">Login here.</a></h3>
            {% endif %}
        </div>
  </section>

{% endblock %}